Weapons:
  Ak47:
    price: 2700
    damage: 5
    fire_rate: 3
    max_bullets: 90
    magazine: 30
    width: 1
    distance: 15
    purchasable: true
  Glock:
    price: 500
    damage: 1
    fire_rate: 1
    max_bullets: 120
    magazine: 30
    width: 1
    distance: 10
    purchasable: false
  M3:
    price: 800
    damage: 20
    fire_rate: 1
    max_bullets: 16
    magazine: 4
    width: 3
    distance: 4
    purchasable: true
  AWP:
    price: 3250
    damage: 250
    fire_rate: 1
    max_bullets: 12
    magazine: 6
    width: 1
    distance: 30
    purchasable: true
  Knife:
    price: 0
    damage: 25
    fire_rate: 1
    max_bullets: 0
    magazine: 0
    width: 2
    distance: 1
    purchasable: false

Player:
  health: 100
  money: 100
  points: 0
  earned_points: 100
  multiplier_points: 12
Timer:
  time_buy: 8
  time_round: 100
  time_bomb: 25
  time_ending: 5

Rounds: 10

RandomWeapons: 
  max_weapons: 5
  Weapons:  # Esto va en porcentajes.
    Ak47: 35
    M3: 50
    AWP: 10
