objects:
  EXPLOSION: "assets/gfx/explosion.png"
  BULLET: "assets/gfx/weapons/bullet.png"
  FONDO_ESPERA: "assets/gfx/screens/espera.jpeg"
  WALL_AZTEC: "assets/gfx/backgrounds/nuke.png"
  WALL_DESIERTO: "assets/gfx/backgrounds/dust.png"
  WALL_ENTRENAMIENTO: "assets/gfx/backgrounds/stone1.jpg"
  FLOOR_AZTEC: "assets/gfx/blockglas.PNG"
  FLOOR_DESIERTO: "assets/gfx/backgrounds/sand1.jpg"
  FLOOR_ENTRENAMIENTO: "assets/gfx/backgrounds/sand1-night.jpg"
  TREE_AZTEC: "assets/gfx/sprites/palmr1.png"
  TREE_DESIERTO: "assets/gfx/sprites/palmr.png"
  TREE_ENTRENAMIENTO: "assets/gfx/sprites/plant1r.png"
  STONE: "assets/gfx/backgrounds/stone1.jpg"
  WATER: "assets/gfx/backgrounds/water4.jpg"
  BOX1: "assets/gfx/backgrounds/b1.jpeg"
  BOX2: "assets/gfx/backgrounds/b2.jpeg"
  BOX3: "assets/gfx/backgrounds/b3.jpeg"
  BOX4: "assets/gfx/backgrounds/b4.jpeg"
  BOX5: "assets/gfx/backgrounds/b5.jpeg"
  BOX6: "assets/gfx/backgrounds/b6.jpeg"
  GRASS: "assets/gfx/backgrounds/gras1.jpg"
  ZONE_BOMBA: "assets/gfx/npc/zonea.png"
  ZONE_BOMBB: "assets/gfx/npc/zoneb.png"
  BOMB: "assets/gfx/weapons/bomb.png"
  TIMER_BOMB: "assets/gfx/icon/bomba.png"
  MONEY: "assets/gfx/icon/money.png"
  MUERTE: "assets/gfx/icon/sangre.png"
  TIENDA: "assets/gfx/icon/tienda.png"
  TIMER: "assets/gfx/icon/timer.png"
  VIDA: "assets/gfx/icon/vida.png"
  BALA: "assets/gfx/icon/bullets.png"
  GLOCK: "assets/gfx/icon/glock_k.png"
  AK47: "assets/gfx/icon/ak47_k.png"
  AWP: "assets/gfx/icon/awp_k.png"
  M3: "assets/gfx/icon/m3_k.png"
  SNIKE: "assets/gfx/icon/knife_k.png"
  MOUSE: "assets/gfx/pointer.png"

terrorist_skins:
  PHOENIX: "assets/gfx/terrorist/t2.png"
  L337_KREW: "assets/gfx/terrorist/t4.png"
  ARCTIC_AVENGER: "assets/gfx/terrorist/t3.png"
  GUERRILLA: "assets/gfx/terrorist/t1_1.png"

counter_terrorist_skins:
  SEAL: "assets/gfx/counterTerrorist/ct2.png"
  GSG9: "assets/gfx/counterTerrorist/ct4.png"
  SAS: "assets/gfx/counterTerrorist/ct3.png"
  GIGN: "assets/gfx/counterTerrorist/ct1.png"

weapons:
  BOMB: "assets/gfx/weapons/bomb.png"
  AK47: "assets/gfx/weapons/ak47v.png"
  AWP: "assets/gfx/weapons/awpv.png"
  M3: "assets/gfx/weapons/m3v.png"
  KNIFE: "assets/gfx/weapons/knife.png"
  GLOCK: "assets/gfx/weapons/glock.png"
